---
title: "R Notebook"
output: html_notebook
---

```{r}
feature_df <- read_csv("lib/cleaned_features.csv")
```

```{r}
recent_a1cs <-
  feature_df %>%
  group_by(id) %>% 
  mutate(n = n()) %>% 
  filter(n > 1) %>% 
  arrange(desc(a1c_date)) %>% 
  slice(c(1, 2))
  # slice(c(1, 2))

newer_a1c <- slice(recent_a1cs, 1) %>% ungroup()

older_a1c <- slice(recent_a1cs, 2) %>% ungroup()
```

```{r}
date_diffs <- newer_a1c$a1c_date - older_a1c$a1c_date

summary(if_else(date_diffs > 1000, date_diffs / 60 / 60 / 24, date_diffs))
```

```{r}
training <- createDataPartition(older_a1c$a1c_value,
                                p = 0.65,
                                list = FALSE)
```

```{r}
lm_df <- select(older_a1c, id, a1c_value, mean_bg_daytime, race)

lm_fit <- lm(a1c_value ~ mean_bg_daytime + race, lm_df[training,])

old_lm_df <- transmute(lm_df, 
                   id,
                   older_a1c_value = a1c_value,
                   pred = predict(lm_fit, newdata = lm_df),
                   resid = a1c_value - pred)

new_lm_df <- select(newer_a1c, 
                    id, 
                    a1c_value,
                    mean_bg_daytime,
                    race) %>% 
  left_join(old_lm_df, by = "id")
```

```{r}
training <- createDataPartition(newer_a1c$a1c_value,
                                p = 0.65,
                                list = FALSE)
```

```{r}
new_lm_outcome <- newer_a1c$a1c_value[-training]

lm_fit_base <- lm(a1c_value ~ 1 + mean_bg_daytime, new_lm_df[training,])
lm_pred_base <- predict(lm_fit_base, new_lm_df[-training,])

lm_fit_race <- lm(a1c_value ~ 1 + mean_bg_daytime + race, new_lm_df[training,])
lm_pred_race <- predict(lm_fit_race, new_lm_df[-training,])

lm_fit_a1c <- lm(a1c_value ~ 1 + mean_bg_daytime + race + older_a1c_value, new_lm_df[training,])
lm_pred_a1c <- predict(lm_fit_a1c, new_lm_df[-training,])

lm_fit_resid <- lm(a1c_value ~ 1 + mean_bg_daytime + race + resid, new_lm_df[training,])
lm_pred_resid <- predict(lm_fit_resid, new_lm_df[-training,])

postResample(lm_pred_base, new_lm_outcome)
postResample(lm_pred_race, new_lm_outcome)
postResample(lm_pred_a1c, new_lm_outcome)
postResample(lm_pred_resid, new_lm_outcome)
```

```{r}
dummied <- 
  dummyVars(a1c_value ~ . - id - a1c_date, older_a1c) %>% 
  predict(older_a1c)

pre_processed <- 
  preProcess(dummied, method = "medianImpute") %>% 
  predict(dummied) %>% 
  as.data.frame()

train_df <- pre_processed[training, ]
test_df <- pre_processed[-training, ]

train_outcome <- older_a1c$a1c_value[training]
test_outcome <- older_a1c$a1c_value[-training]

fit_control <- trainControl(method = "repeatedcv",
                            number = 5,
                            verboseIter = FALSE,
                            allowParallel = TRUE)

lambdas <- 10 ^ seq(-3, 1, length = 100)

lasso_fit <- train(train_df,
                   train_outcome,
                   method = "glmnet",
                   tuneGrid = data.frame(alpha = 1,
                                          lambda = lambdas),
                   trControl = fit_control)
```

```{r}
lasso_pred <- predict(lasso_fit, test_df)
(lasso_results <- postResample(lasso_pred, test_outcome))
```

```{r}
older_a1c_w_resid <-
  older_a1c %>% 
  mutate(resid = a1c_value - predict(lasso_fit, pre_processed)) %>% 
  select(id, resid)

newer_a1c_w_resid <-
  inner_join(newer_a1c,
             older_a1c_w_resid,
             by = "id")
```

```{r}
training <- createDataPartition(newer_a1c$a1c_value,
                                p = 0.65,
                                list = FALSE)

train_outcome <- newer_a1c$a1c_value[training]
test_outcome <- newer_a1c$a1c_value[-training]
```

```{r}
lm_df <- select(newer_a1c_w_resid, a1c_value, mean_bg_daytime, race, resid)

lm_fit <- lm(a1c_value ~ 1 + mean_bg_daytime + race, lm_df[training, ])
lm_pred <- predict(lm_fit, lm_df)

lm_resid_fit <- lm(a1c_value ~ ., lm_df[training, ])
lm_resid_pred <- predict(lm_resid_fit, lm_df)

gmi <- 3.31 + 0.02392 * lm_df$mean_bg_daytime

(gmi_results <- postResample(gmi[-training], test_outcome))
(lm_results <- postResample(lm_pred[-training], test_outcome))
(lm_resid_results <- postResample(lm_resid_pred[-training], test_outcome))
```

```{r}
dummied <- 
  dummyVars(a1c_value ~ . - id - a1c_date, newer_a1c) %>% 
  predict(newer_a1c)

pre_processed <- 
  preProcess(dummied, method = "medianImpute") %>% 
  predict(dummied) %>% 
  as.data.frame()

train_df <- pre_processed[training, ]
test_df <- pre_processed[-training, ]

train_outcome <- newer_a1c$a1c_value[training]
test_outcome <- newer_a1c$a1c_value[-training]

fit_control <- trainControl(method = "repeatedcv",
                            number = 5,
                            verboseIter = FALSE,
                            allowParallel = TRUE)

lambdas <- 10 ^ seq(-3, 1, length = 100)

lasso_fit <- train(train_df,
                   train_outcome,
                   method = "glmnet",
                   tuneGrid = data.frame(alpha = 1,
                                          lambda = lambdas),
                   trControl = fit_control)
```

```{r}
lasso_pred <- predict(lasso_fit, test_df)
(lasso_results <- postResample(lasso_pred, test_outcome))
```

```{r}
dummied <- 
  dummyVars(a1c_value ~ . - id - a1c_date, newer_a1c_w_resid) %>% 
  predict(newer_a1c_w_resid)

pre_processed <- 
  preProcess(dummied, method = "medianImpute") %>% 
  predict(dummied) %>% 
  as.data.frame()

train_df <- pre_processed[training, ]
test_df <- pre_processed[-training, ]

train_outcome <- newer_a1c_w_resid$a1c_value[training]
test_outcome <- newer_a1c_w_resid$a1c_value[-training]

fit_control <- trainControl(method = "repeatedcv",
                            number = 5,
                            verboseIter = FALSE,
                            allowParallel = TRUE)

lambdas <- 10 ^ seq(-3, 1, length = 100)

lasso_fit <- train(train_df,
                   train_outcome,
                   method = "glmnet",
                   tuneGrid = data.frame(alpha = 1,
                                          lambda = lambdas),
                   trControl = fit_control)
```

```{r}
lasso_pred <- predict(lasso_fit, test_df)
(lasso_results <- postResample(lasso_pred, test_outcome))
```


